### ISSUE TITLE
Create a Makefile for Texty

### ISSUE THREAD

**Issue by ryanteddy** [ryanteddy/texty#1]
Create a Makefile for compiling the whole project. It should included with the proper warning & optimization flags.
Also the C17 standard must be followed.

**Comment by Hridoy-31** [comment]
Hello, @ryanteddy, can I work on this issue ?? Thanks in advance :)

**Comment by ryanteddy** [comment]
Yes, obviously !! You can carry on. I'm looking for your valuable PR. Thank you !
