### ISSUE TITLE
Dynamic size of the terminal windows

### ISSUE THREAD

**Issue by ryanteddy** [ryanteddy/texty#3]
Because of Texty editor runs entirely in terminal. It is very much essential to use dynamic size of the terminal. The bad side for fixed terminal size is it is hard-coded. It will not depend on the users resolution, which is considered bad for text manipulation as far as it is used for text editing.

So, the implementation of dynamic terminal size is so much appreciated. 

If you need any clearance, please inform me without any hesitation.

**Comment by Hridoy-31** [comment]
Hello @ryanteddy, can I work on this issue ? As a beginner, hard issues might be super hard for me, but I want to give it a try. Thanks in Advance !

**Comment by ryanteddy** [comment]
Yeah ! Of course. Go ahead. I'm looking for your valuable PR. :sunglasses:
