### ISSUE TITLE
VIM-like `~` in front of every row

### ISSUE THREAD

**Issue by ryanteddy** [ryanteddy/texty#5]
I'd like to implement the feature of `~` in front of every rows up to the terminal window size. Just I want to make a vim like enhancement.

@Hridoy-31 you've already implement the dynamic terminal window size. I want you to take this issue if you are free enough.
Just let me know, I'll assign you. Then you can contribute on this issue.

**Comment by Hridoy-31** [comment]
Hey @ryanteddy, I can work on that. Thank you for the opportunity ! ❤️
