### ISSUE TITLE
Implement the cursor moving functionality with Arrow keys

### ISSUE THREAD

**Issue by ryanteddy** [ryanteddy/texty#8]
The whole dynamic terminal window size has been developed. Now, I like to move the cursor through the editor with arrow keys. Implement this feature.

For the common usage part, you can implement this feature & map the keys with the WASD keys, so that it can be navigated by those keys also.

**Comment by Hridoy-31** [comment]
Hello @ryanteddy, can I work on this issue ? I want to give it a try.

**Comment by ryanteddy** [comment]
Sure. I've assigned you. Looking for your valuable PR !
